### ISSUE TITLE
Filter by bounding box example

### ISSUE THREAD

**Issue by willfarrell** [gordonfn/datastream-api-public#26]
Add example to docs on how to filter by bounding box (use normalized coords)

**Comment by willfarrell** [comment]
Is `bbox` actually in the odata spec? If not, please roll this commit back.

We already support this by using a filter with 4 compare arguments against. Was just looking for that as an example in the docs.

**Comment by mandy-kudos** [comment]
It uses filter eq so it follows odata conventions. In my option we should keep it, it will perform much faster than the comparison operators.

**Comment by mandy-kudos** [comment]
Okay tried to test this for time and for most endpoints you can't search in a bounding box using comparison operators. I think this makes it easy to get results from all three endpoints in a bounding box

**Comment by willfarrell** [comment]
If we enable lat,lng (normalized) on the request it should work, if it doesn't there is a bug. This implementation also allows the user to choose what coord system they want to filter by which is nice, but adds complexity. Our userbase having GIS knowledge is very unlikely. I think simplicity is the way to go.

**Comment by mandy-kudos** [comment]
Fixed

**Comment by willfarrell** [comment]
Can you add `LatitudeNormalized` and `LongitudeNormalized` please as these will be more likely used.

**Comment by mandy-kudos** [comment]
Done
