### ISSUE TITLE
API Returning Wrong Information

### ISSUE THREAD

**Issue by patrickleclair-GORDONFN** [gordonfn/datastream-api-public#28]
This request gives a 200 and returns data, but it returns only 10 rows of Molybdenum data instead of 1000 of pH

API Call: `https://api.datastream.org/v1/odata/v4/Observations?$filter=CharacteristicName  eq  pH and ActivityStartTimeStamp gt '2019-01-01'&$orderby=ActivityStartTimeStamp&$select=Id,DatasetId&$top=1000&$count=false`

data:   
[API Test.txt](https://github.com/gordonfn/datastream-api-public/files/5170342/API.Test.txt)

**Comment by mandy-kudos** [comment]
Fixed now! There was an issue with count. Note that the API call should be as below (quotations were missing from around pH):
`https://api.datastream.org/v1/odata/v4/Observations?$filter=CharacteristicName eq 'pH' and ActivityStartDate gt '2019-01-01'&$orderby=ActivityStartDate&$select=Id,DatasetId&$top=1000&$count=false`
