### ISSUE TITLE
Encoding Issues

### ISSUE THREAD

**Issue by patrickleclair-GORDONFN** [gordonfn/datastream-api-public#29]
When I try to run the request I get a 400 error, but when I remove the `%20` from the URL after encoding it's fine.

400 request: `https://api.datastream.org/v1/odata/v4/Observations?$filter=CharacteristicName%20%20eq%20%20pH%20and%20ActivityStartTimeStamp%20gt%20'2019-01-01'&$orderby=ActivityStartTimeStamp&$select=Id,DatasetId&$top=10&$count=false`

**Comment by mandy-kudos** [comment]
I believe that this was the same issue as #28. Note that you need single quotes around pH:
`CharacteristicName%20eq%20%27pH%27%20and%20ActivityStartDate%20gt%20%272019-01-01%27`
