### ISSUE TITLE
Wrong logic applied to all `or`

### ISSUE THREAD

**Issue by willfarrell** [gordonfn/datastream-api-public#30]
/v1/odata/v4/Metadata?$top=5&$select=Id,Name,Doi&$filter=Id%20eq%20%27b6a1a028-8daf-48c6-b419-12a5c2a76d6c%27%20or%20Id%20eq%20%27f3877597-9114-4ace-ad6f-e8a68435c0ba%27%20or%20Id%20eq%20%27cf1547d6-497b-4d58-903e-b440326ffef0%27

makes SQL:

select m.id AS "Id", m.name AS "Name", m.doi AS "Doi" from "dataset"."metadata" as "m" where ("m"."id" = 'b6a1a028-8daf-48c6-b419-12a5c2a76d6c' and ("m"."id" = 'f3877597-9114-4ace-ad6f-e8a68435c0ba' or "m"."id" = 'cf1547d6-497b-4d58-903e-b440326ffef0')) limit 5

**Comment by mandy-kudos** [comment]
This will never be perfect because of the way the parser works but this case is fixed now.
